-- MonitorLite 通用版数据表 (H2 PostgreSQL兼容模式)
-- 所有配置均可从前端编辑, 即时生效

CREATE TABLE IF NOT EXISTS t_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key VARCHAR(200) UNIQUE NOT NULL,
    config_value VARCHAR(2000),
    config_label VARCHAR(200),
    config_group VARCHAR(50) DEFAULT 'general',
    sort_order INT DEFAULT 0,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ===== 目标配置 =====

-- 监控端点 (用户自定义HTTP接口)
CREATE TABLE IF NOT EXISTS t_endpoint (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    url VARCHAR(500) NOT NULL,
    method VARCHAR(10) DEFAULT 'GET',
    enabled BOOLEAN DEFAULT TRUE,
    check_interval INT DEFAULT 300,
    sort_order INT DEFAULT 0
);

-- 外部API探测目标
CREATE TABLE IF NOT EXISTS t_ext_api (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    host VARCHAR(200) NOT NULL,
    port INT DEFAULT 80,
    enabled BOOLEAN DEFAULT TRUE,
    sort_order INT DEFAULT 0
);

-- 基础设施探测目标
CREATE TABLE IF NOT EXISTS t_infra_target (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    target_type VARCHAR(30) DEFAULT 'tcp',
    host VARCHAR(200) NOT NULL,
    port INT DEFAULT 80,
    enabled BOOLEAN DEFAULT TRUE,
    sort_order INT DEFAULT 0
);

-- K8s集群监控目标 (信创: 华为CCE/阿里ACK/腾讯TKE/KubeSphere/Rainbond等)
CREATE TABLE IF NOT EXISTS t_k8s_cluster (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    cluster_type VARCHAR(50) DEFAULT 'Kubernetes',
    api_server VARCHAR(500) NOT NULL,
    token VARCHAR(2000) DEFAULT '',
    namespace VARCHAR(100) DEFAULT 'default',
    enabled BOOLEAN DEFAULT TRUE,
    sort_order INT DEFAULT 0
);

-- Docker主机监控 (信创: 麒麟V10/统信UOS + 海光/鲲鹏架构)
CREATE TABLE IF NOT EXISTS t_docker_host (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    host VARCHAR(200) NOT NULL,
    port INT DEFAULT 2375,
    tls_enabled BOOLEAN DEFAULT FALSE,
    enabled BOOLEAN DEFAULT TRUE,
    sort_order INT DEFAULT 0
);

-- 自定义SQL查询面板
CREATE TABLE IF NOT EXISTS t_custom_query (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    query_type VARCHAR(30) DEFAULT 'metric',
    datasource_name VARCHAR(100) DEFAULT 'H2',
    query_sql VARCHAR(2000) NOT NULL,
    display_type VARCHAR(20) DEFAULT 'cards',
    refresh_interval INT DEFAULT 300,
    enabled BOOLEAN DEFAULT TRUE,
    sort_order INT DEFAULT 0
);

-- 外部数据源
CREATE TABLE IF NOT EXISTS t_datasource (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL,
    driver_class VARCHAR(200) NOT NULL,
    jdbc_url VARCHAR(500) NOT NULL,
    username VARCHAR(100),
    password VARCHAR(200),
    max_pool_size INT DEFAULT 2,
    enabled BOOLEAN DEFAULT TRUE
);

-- ===== 运行时数据 =====

CREATE TABLE IF NOT EXISTS t_system_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cpu_usage DOUBLE,
    cpu_load DOUBLE,
    mem_total BIGINT,
    mem_used BIGINT,
    mem_percent DOUBLE,
    disk_total BIGINT,
    disk_used BIGINT,
    disk_percent DOUBLE,
    jvm_total BIGINT,
    jvm_used BIGINT,
    jvm_max BIGINT,
    snap_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS t_alert (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_level VARCHAR(20),
    target_type VARCHAR(50),
    target_name VARCHAR(100),
    message VARCHAR(500),
    acked BOOLEAN DEFAULT FALSE,
    ack_time TIMESTAMP NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    recover_time TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS t_operation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation VARCHAR(50),
    target VARCHAR(200),
    result VARCHAR(20),
    detail VARCHAR(1000),
    operator VARCHAR(50) DEFAULT 'admin',
    op_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS t_script_run_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    script_name VARCHAR(200),
    params VARCHAR(500),
    status VARCHAR(20),
    exit_code INT,
    output CLOB,
    start_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    end_time TIMESTAMP NULL
);

-- ===== 默认演示数据 (评委开箱即看) =====
INSERT INTO t_ext_api (name, host, port, enabled) SELECT * FROM (
    SELECT '示例API_1' AS n, '192.168.1.100' AS h, 8080 AS p, TRUE AS e UNION ALL
    SELECT '示例API_2', '192.168.1.101', 8081, TRUE UNION ALL
    SELECT '东方通TongWeb', '192.168.1.110', 9011, TRUE UNION ALL
    SELECT '金蝶Apusic', '192.168.1.111', 8088, TRUE UNION ALL
    SELECT '宝兰德BES', '192.168.1.112', 18080, TRUE UNION ALL
    SELECT '中创InforSuite', '192.168.1.113', 8080, TRUE
) x WHERE NOT EXISTS (SELECT 1 FROM t_ext_api);

INSERT INTO t_infra_target (name, target_type, host, port, enabled) SELECT * FROM (
    SELECT '示例数据库' AS n, 'tcp' AS t, '192.168.1.200' AS h, 5432 AS p, TRUE AS e UNION ALL
    SELECT '示例Redis', 'tcp', '192.168.1.201', 6379, TRUE UNION ALL
    SELECT '示例SFTP', 'tcp', '192.168.1.202', 22, TRUE UNION ALL
    SELECT '达梦DM', 'db', '192.168.1.210', 5236, TRUE UNION ALL
    SELECT '人大金仓Kingbase', 'db', '192.168.1.211', 54321, TRUE UNION ALL
    SELECT '南大通用GBase', 'db', '192.168.1.212', 5258, TRUE UNION ALL
    SELECT '瀚高HighGo', 'db', '192.168.1.213', 5866, TRUE UNION ALL
    SELECT '神通Oscar', 'db', '192.168.1.214', 2003, TRUE
) x WHERE NOT EXISTS (SELECT 1 FROM t_infra_target);

INSERT INTO t_k8s_cluster (name, cluster_type, api_server, token, namespace, enabled) SELECT * FROM (
    SELECT '华为CCE集群' AS n, '华为CCE' AS t, 'https://192.168.1.220:6443' AS a, '' AS tok, 'default' AS ns, TRUE AS e UNION ALL
    SELECT 'KubeSphere集群', 'KubeSphere', 'https://192.168.1.221:6443', '', 'default', TRUE UNION ALL
    SELECT '阿里ACK集群', '阿里ACK', 'https://192.168.1.222:6443', '', 'default', TRUE
) x WHERE NOT EXISTS (SELECT 1 FROM t_k8s_cluster);

INSERT INTO t_docker_host (name, host, port, tls_enabled, enabled) SELECT * FROM (
    SELECT '麒麟Docker节点' AS n, '192.168.1.230' AS h, 2375 AS p, FALSE AS tls, TRUE AS e UNION ALL
    SELECT '统信UOS节点', '192.168.1.231', 2375, FALSE, TRUE UNION ALL
    SELECT '海光容器节点', '192.168.1.232', 2376, TRUE, TRUE
) x WHERE NOT EXISTS (SELECT 1 FROM t_docker_host);

INSERT INTO t_endpoint (name, url, method, enabled) SELECT * FROM (
    SELECT '首页' AS n, 'http://localhost:8080/' AS u, 'GET' AS m, TRUE AS e UNION ALL
    SELECT '健康检查', 'http://localhost:8080/health', 'GET', TRUE
) x WHERE NOT EXISTS (SELECT 1 FROM t_endpoint);

INSERT INTO t_custom_query (name, query_type, query_sql, display_type, enabled) SELECT * FROM (
    SELECT 'H2表统计' AS n, 'metric' AS t, 'SELECT COUNT(1) AS tables FROM INFORMATION_SCHEMA.TABLES' AS s, 'cards' AS d, TRUE AS e
) x WHERE NOT EXISTS (SELECT 1 FROM t_custom_query);
